# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/courserethinking',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/courserethinking',
                'lib_path': 'courserethinking'},
  'syms': {'courserethinking.core': {'courserethinking.core.foo': ('core.html#foo', 'courserethinking/core.py')}}}